### ISSUE TITLE
SFML example crashes when compiled with g++ 5

### ISSUE THREAD

**Issue by jpleau** [SFML/SFML#936]
Hi.

This example fails to run correctly when built with g++ 5.2.1 on Debian sid. This is with using SFML 2.3.1 from Debian repos. (example taken from: http://www.sfml-dev.org/tutorials/2.3/start-linux.php)

It runs successfully using g++-4.9.3

```
#include <SFML/Graphics.hpp>

int main()
{
    sf::RenderWindow window(sf::VideoMode(200, 200), "SFML works!");
    sf::CircleShape shape(100.f);
    shape.setFillColor(sf::Color::Green);

    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            if (event.type == sf::Event::Closed)
                window.close();
        }

        window.clear();
        window.draw(shape);
        window.display();
    }

    return 0;
}
```

Output:
```
jason ~/sfml make
g++ -c main.cpp  -std=c++14 -o main.o 
g++ -o run main.o -lsfml-graphics -lsfml-window -lsfml-system 
jason ~/sfml ./run
*** Error in `./run': free(): invalid pointer: 0x0000000002342368 ***
[1]    5599 abort      ./run


bt:

#0  0x00007ffff6b63107 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff6b644e8 in __GI_abort () at abort.c:89
#2  0x00007ffff6ba1214 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7ffff6c94000 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff6ba69ee in malloc_printerr (action=1, str=0x7ffff6c900be "free(): invalid pointer", ptr=<optimized out>) at malloc.c:4996
#4  0x00007ffff6ba76f6 in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
#5  0x00000000004015f0 in __gnu_cxx::new_allocator<unsigned int>::deallocate (this=0x7fffffffe4c0, __p=0x642368) at /usr/lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/c++/5.2.1/ext/new_allocator.h:110
#6  0x0000000000401580 in std::allocator_traits<std::allocator<unsigned int> >::deallocate (__a=..., __p=0x642368, __n=4294967297)
    at /usr/lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/c++/5.2.1/bits/alloc_traits.h:386
#7  0x0000000000401532 in std::__cxx11::basic_string<unsigned int, std::char_traits<unsigned int>, std::allocator<unsigned int> >::_M_destroy (this=0x7fffffffe4c0, __size=4294967296)
    at /usr/lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/c++/5.2.1/bits/basic_string.h:185
#8  0x0000000000401441 in std::__cxx11::basic_string<unsigned int, std::char_traits<unsigned int>, std::allocator<unsigned int> >::_M_dispose (this=0x7fffffffe4c0)
    at /usr/lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/c++/5.2.1/bits/basic_string.h:180
#9  0x00000000004013d8 in std::__cxx11::basic_string<unsigned int, std::char_traits<unsigned int>, std::allocator<unsigned int> >::~basic_string (this=0x7fffffffe4c0)
    at /usr/lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/c++/5.2.1/bits/basic_string.h:544
#10 0x0000000000401365 in sf::String::~String (this=0x7fffffffe4c0) at /usr/include/SFML/System/String.hpp:44
#11 0x00000000004010ef in main () at main.cpp:5
```

g++ -v:
```
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 5.2.1-14' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --with-arch-32=i586 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.2.1 20150730 (Debian 5.2.1-14) 
```

**Comment by eXpl0it3r** [comment]
Please follow the [contribution guidelines](http://www.sfml-dev.org/contribute.php). We like to use the issue tracker for confirmed bugs only.
If you encounter issues like the one posted here, make sure to use the forum instead to discuss the origin.

You're running Debian Sid, you should expect stuff to not just always work. It seems like an incompatibility in the runtime library used for the SFML binaries and the runtime library used for the example you try to build. GCC 4.9.x and GCC 5.1.x are not fully compatible, as such if you use SFML built for GCC 4.9.x but use GCC 5.1.x things might fail.

**Comment by binary1248** [comment]
Just tested self-built 2.3.1 with gcc 5.2.1, works for me. If you are going to use sid, you should get used to building a lot of things yourself. Like eXpl0it3r said, the packages in the repository will always lag behind, sometimes more and sometimes less. If a package built specifically for sid is broken, you will have to report it to the package maintainer and not us.

**Comment by jpleau** [comment]
Indeed the package was probably built using g++ 4.9.3, and they probably enabled the new ABI in g++ 5 in sid. Should have thought about that

Sorry for the noise...

**Comment by jcowgill** [comment]
Yep, 5.2.1-13 has the new C++ ABI enabled on it so compiling against the majority of C++ libraries in sid is currently broken. Anything built with GCC 4.9 should still work. It should get resolved in a few weeks once all the C++ library packages have been rebuilt.

List of libraries affected:
https://bugs.debian.org/cgi-bin/pkgreport.cgi?tag=libstdc%2B%2B-cxx11;users=debian-gcc@lists.debian.org
